package com.socialindia.expencesmgmt;
// default package
// Generated Aug 17, 2016 5:12:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * MvpExpenceTbl generated by hbm2java
 */
public class ExpenceTblVO implements java.io.Serializable {

	private Integer expnId;
	private String expenceFor;
	private String noOfProduct;
	private String productPerAmt;
	private String expenceTotAmt;
	private String descr;
	private String expenceStatus;
	private String entryByGrp;
	private String entryBy;
	private Date entryDatetime;
	private Date modifyDatetime;
	private String societyname;
	

	public ExpenceTblVO(String expenceFor, String noOfProduct,
			String descr,	String expenceTotAmt,String societyname,String productPerAmt,  
			 Integer expnId) 
	{
		this.expenceFor = expenceFor;
		this.noOfProduct = noOfProduct;
		this.descr = descr;
		this.expenceTotAmt = expenceTotAmt;
		this.societyname=societyname;
		this.productPerAmt = productPerAmt;
		this.expnId = expnId;
		
	}

	
	public String getSocietyname() {
		return societyname;
	}


	public void setSocietyname(String societyname) {
		this.societyname = societyname;
	}


	public Integer getExpnId() {
		return this.expnId;
	}

	public void setExpnId(Integer expnId) {
		this.expnId = expnId;
	}

	public String getExpenceFor() {
		return this.expenceFor;
	}

	public void setExpenceFor(String expenceFor) {
		this.expenceFor = expenceFor;
	}

	

	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	
	public Date getEntryDatetime() {
		return this.entryDatetime;
	}

	public void setEntryDatetime(Date entryDatetime) {
		this.entryDatetime = entryDatetime;
	}

	public Date getModifyDatetime() {
		return this.modifyDatetime;
	}

	public void setModifyDatetime(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public String getNoOfProduct() {
		return noOfProduct;
	}

	public void setNoOfProduct(String noOfProduct) {
		this.noOfProduct = noOfProduct;
	}

	public String getProductPerAmt() {
		return productPerAmt;
	}

	public void setProductPerAmt(String productPerAmt) {
		this.productPerAmt = productPerAmt;
	}

	public String getExpenceTotAmt() {
		return expenceTotAmt;
	}

	public void setExpenceTotAmt(String expenceTotAmt) {
		this.expenceTotAmt = expenceTotAmt;
	}

	public String getExpenceStatus() {
		return expenceStatus;
	}

	public void setExpenceStatus(String expenceStatus) {
		this.expenceStatus = expenceStatus;
	}

	public String getEntryByGrp() {
		return entryByGrp;
	}

	public void setEntryByGrp(String entryByGrp) {
		this.entryByGrp = entryByGrp;
	}

	public String getEntryBy() {
		return entryBy;
	}

	public void setEntryBy(String entryBy) {
		this.entryBy = entryBy;
	}
	
	

}
