package com.socialindia.societyMgmt;

import java.util.Date;

/**
 * SocietyWingsDetailTbl generated by hbm2java
 */
public class SocietyWingsDetailTbl implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer wingsId;
	private String wingsName;
	private Integer status;
	private Integer enrtyBy;
	private Date entryDate;
	private Date modifyDate;


	public SocietyWingsDetailTbl( String wingsName) {
		
		this.wingsName = wingsName;
		
	}

	public Integer getWingsId() {
		return this.wingsId;
	}

	public void setWingsId(Integer wingsId) {
		this.wingsId = wingsId;
	}


	public String getWingsName() {
		return this.wingsName;
	}

	public void setWingsName(String wingsName) {
		this.wingsName = wingsName;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getEnrtyBy() {
		return this.enrtyBy;
	}

	public void setEnrtyBy(Integer enrtyBy) {
		this.enrtyBy = enrtyBy;
	}

	public Date getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

}
