package com.socialindia.tendermgmt;
// default package
// Generated Aug 17, 2016 5:12:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;



/**
 * MvpTenderDocTbl generated by hbm2java
 */
public class TenderDocTblVO implements java.io.Serializable {

	private Integer tenderDocId;
	private String societyMstTbl;
	private String usrRegTbl;
	private String mvpTenderTbl;
	private String documentName;
	private String documentType;
	private Integer entryBy;
	private Date entryDatetime;
	private Date modifyDatetime;
	private String documentpath;
	private String filedownloadurl;
	
	

	/*public TenderDocTblVO(SocietyMstTbl societyMstTbl, UsrRegTbl usrRegTbl,
			MvpTenderTbl mvpTenderTbl, String documentName,
			String documentType, Integer entryBy, Date entryDatetime,
			Date modifyDatetime) {
		this.societyMstTbl = societyMstTbl;
		this.usrRegTbl = usrRegTbl;
		this.mvpTenderTbl = mvpTenderTbl;
		this.documentName = documentName;
		this.documentType = documentType;
		this.entryBy = entryBy;
		this.entryDatetime = entryDatetime;
		this.modifyDatetime = modifyDatetime;
	}*/

	public TenderDocTblVO(String docfilename, String docfilename2,String docfilepath,String filedownloadurl) {
		// TODO Auto-generated constructor stub
		this.documentName =docfilename;
		this.documentType=docfilename2;
		this.documentpath =docfilepath;
		this.filedownloadurl=filedownloadurl;
	}
	

	public Integer getTenderDocId() {
		return this.tenderDocId;
	}

	

	public String getSocietyMstTbl() {
		return societyMstTbl;
	}

	public void setSocietyMstTbl(String societyMstTbl) {
		this.societyMstTbl = societyMstTbl;
	}

	public String getUsrRegTbl() {
		return usrRegTbl;
	}

	public void setUsrRegTbl(String usrRegTbl) {
		this.usrRegTbl = usrRegTbl;
	}

	public String getMvpTenderTbl() {
		return mvpTenderTbl;
	}

	public void setMvpTenderTbl(String mvpTenderTbl) {
		this.mvpTenderTbl = mvpTenderTbl;
	}

	public void setTenderDocId(Integer tenderDocId) {
		this.tenderDocId = tenderDocId;
	}

	public String getDocumentName() {
		return this.documentName;
	}

	public void setDocumentName(String documentName) {
		this.documentName = documentName;
	}

	public String getDocumentType() {
		return this.documentType;
	}

	public void setDocumentType(String documentType) {
		this.documentType = documentType;
	}

	public Integer getEntryBy() {
		return this.entryBy;
	}

	public void setEntryBy(Integer entryBy) {
		this.entryBy = entryBy;
	}

	public Date getEntryDatetime() {
		return this.entryDatetime;
	}

	public void setEntryDatetime(Date entryDatetime) {
		this.entryDatetime = entryDatetime;
	}

	public Date getModifyDatetime() {
		return this.modifyDatetime;
	}

	public void setModifyDatetime(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public String getDocumentpath() {
		return documentpath;
	}

	public void setDocumentpath(String documentpath) {
		this.documentpath = documentpath;
	}


	public String getFiledownloadurl() {
		return filedownloadurl;
	}


	public void setFiledownloadurl(String filedownloadurl) {
		this.filedownloadurl = filedownloadurl;
	}
	

}
