package com.socialindia.tendermgmt;// Generated Aug 17, 2016 5:12:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * MvpTenderTbl generated by hbm2java
 */
public class TenderTblVO implements java.io.Serializable {

	private Integer tenderId;
	private String usrRegTbl;
	private String groupMstTbl;
	private String tenderName;
	private String tenderDate;
	private Float tenderAmount;
	private String tenderDetails;
	private String entryBy;
	private String entryDatetime;
	private String societyname;
	
	public String getSocietyname() {
		return societyname;
	}
	public void setSocietyname(String societyname) {
		this.societyname = societyname;
	}
	public TenderTblVO(String tendertitle, String tenderstartdate, String tenderdesc, String tenderposedby, Integer tenderid2, String tendersocietyname) {
		
		this.tenderName = tendertitle;
		this.tenderDate = tenderstartdate;
		this.tenderDetails = tenderdesc;
		this.entryBy = tenderposedby;
		this.tenderId = tenderid2;
		this.societyname = tendersocietyname;
		
	}
	public Integer getTenderId() {
		return this.tenderId;
	}
	public void setTenderId(Integer tenderId) {
		this.tenderId = tenderId;
	}
	public String getUsrRegTbl() {
		return usrRegTbl;
	}
	public void setUsrRegTbl(String usrRegTbl) {
		this.usrRegTbl = usrRegTbl;
	}
	public String getGroupMstTbl() {
		return groupMstTbl;
	}

	public void setGroupMstTbl(String groupMstTbl) {
		this.groupMstTbl = groupMstTbl;
	}

	public String getTenderName() {
		return this.tenderName;
	}

	public void setTenderName(String tenderName) {
		this.tenderName = tenderName;
	}

	

	public Float getTenderAmount() {
		return this.tenderAmount;
	}

	public void setTenderAmount(Float tenderAmount) {
		this.tenderAmount = tenderAmount;
	}

	public String getTenderDetails() {
		return this.tenderDetails;
	}

	public void setTenderDetails(String tenderDetails) {
		this.tenderDetails = tenderDetails;
	}

	public String getEntryBy() {
		return entryBy;
	}
	public void setEntryBy(String entryBy) {
		this.entryBy = entryBy;
	}

	public String getTenderDate() {
		return tenderDate;
	}

	public void setTenderDate(String tenderDate) {
		this.tenderDate = tenderDate;
	}

	public String getEntryDatetime() {
		return entryDatetime;
	}

	public void setEntryDatetime(String entryDatetime) {
		this.entryDatetime = entryDatetime;
	}
}
