package com.socialindia.forum;

// default package
// Generated Jul 21, 2016 6:06:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;


/**
 * MvpFourmTopicsTbl generated by hbm2java
 */
public class MvpFourmTopicsTblVO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer topicsId;
	private int groupCode;
	private int userId;
	private String topicsName;
	private String topicsDesc;
	private String keyForSearch;
	private Date validOnDate;
	private Integer status;
	private Integer entryBy;
	private Date entryDatetime;
	private Date modifyDatetime;
	private String entryDate;
	
	private String firstName;
	private String groupName;
	private String lastName;
	private String mobileNo;
	private int topicsCount;
	
	private String fvalidDate;
	public MvpFourmTopicsTblVO() {
	}

	public MvpFourmTopicsTblVO(int topicsid,String fname,String grpname,String topicsName,Integer entryBy,String entryDatetime,
			String lastName,String mobileNo,int topicscount,int userId) {
		this.topicsId = topicsid;
		this.firstName = fname;
		this.groupName = grpname;
		this.topicsName = topicsName;
		this.entryBy = entryBy;
		this.entryDate = entryDatetime;
		this.lastName = lastName;
		this.mobileNo = mobileNo;
		this.topicsCount = topicscount;
		this.userId = userId;
	}

	public Integer getTopicsId() {
		return this.topicsId;
	}

	public void setTopicsId(Integer topicsId) {
		this.topicsId = topicsId;
	}

	
	public String getTopicsName() {
		return this.topicsName;
	}

	public void setTopicsName(String topicsName) {
		this.topicsName = topicsName;
	}

	public String getTopicsDesc() {
		return this.topicsDesc;
	}

	public void setTopicsDesc(String topicsDesc) {
		this.topicsDesc = topicsDesc;
	}

	public String getKeyForSearch() {
		return this.keyForSearch;
	}

	public void setKeyForSearch(String keyForSearch) {
		this.keyForSearch = keyForSearch;
	}

	public Date getValidOnDate() {
		return this.validOnDate;
	}

	public void setValidOnDate(Date validOnDate) {
		this.validOnDate = validOnDate;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getEntryBy() {
		return this.entryBy;
	}

	public void setEntryBy(Integer entryBy) {
		this.entryBy = entryBy;
	}

	public Date getEntryDatetime() {
		return this.entryDatetime;
	}

	public void setEntryDatetime(Date entryDatetime) {
		this.entryDatetime = entryDatetime;
	}

	public Date getModifyDatetime() {
		return this.modifyDatetime;
	}

	public void setModifyDatetime(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public int getGroupCode() {
		return groupCode;
	}

	public void setGroupCode(int groupCode) {
		this.groupCode = groupCode;
	}

	public int getUserId() {
		return userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getEntryDate() {
		return entryDate;
	}

	public void setEntryDate(String entryDate) {
		this.entryDate = entryDate;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getGroupName() {
		return groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getMobileNo() {
		return mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	public int getTopicsCount() {
		return topicsCount;
	}
	public void setTopicsCount(int topicsCount) {
		this.topicsCount = topicsCount;
	}

	public String getFvalidDate() {
		return fvalidDate;
	}

	public void setFvalidDate(String fvalidDate) {
		this.fvalidDate = fvalidDate;
	}


}
