package com.letspay.uam.persistense;

// default package
// Generated Jun 14, 2016 2:48:12 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SocietyMstTbl generated by hbm2java
 */
public class SocietyMstTbl implements java.io.Serializable {

	private Integer societyId;
	private TownshipMstTbl townshipId;
	private String societyUniqyeId;
	private String societyName;
	private Integer entryby;
	private Date entryDatetime;
	private Date modifyDatetime;
	private int noOfMembers;

	private String mobileNo;
	private String emailId;
	private String isdcode;

	private String townshipName;
	private String activationKey;
	private String countryName;
	private String stateName;
	private String cityName;
	private String pinCode;
	private String address;
	private int groupCode;

	private String noOfBlocksWings;
	private String registerNo;
	private String colourCode;
	private String imprintName;
	private String logoImage;
	private String icoImage;
	private String ivrSmobnum;
	
	private String gstin;
	private String hsn;

	public SocietyMstTbl(int societyId, String townshipName,
			String societyname, String activationKey, String countryname,
			String statename, String cityname, int groupcode, String emailid) {

		this.societyId = societyId;
		this.townshipName = townshipName;
		this.societyName = societyname;
		this.activationKey = activationKey;
		this.countryName = countryname;
		this.stateName = statename;
		this.cityName = cityname;
		this.groupCode = groupcode;
		this.emailId = emailid;
	}

	public SocietyMstTbl(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public String getIvrSmobnum() {
		return ivrSmobnum;
	}

	public void setIvrSmobnum(String ivrSmobnum) {
		this.ivrSmobnum = ivrSmobnum;
	}

	public SocietyMstTbl(int societyId, String societyName) {

		this.societyId = societyId;
		this.societyName = societyName;
	}

	public Integer getSocietyId() {
		return this.societyId;
	}

	public void setSocietyId(Integer societyId) {
		this.societyId = societyId;
	}

	public TownshipMstTbl getTownshipId() {
		return townshipId;
	}

	public void setTownshipId(TownshipMstTbl townshipId) {
		this.townshipId = townshipId;
	}

	public String getSocietyUniqyeId() {
		return this.societyUniqyeId;
	}

	public void setSocietyUniqyeId(String societyUniqyeId) {
		this.societyUniqyeId = societyUniqyeId;
	}

	public String getSocietyName() {
		return this.societyName;
	}

	public void setSocietyName(String societyName) {
		this.societyName = societyName;
	}

	public Integer getEntryby() {
		return this.entryby;
	}

	public void setEntryby(Integer entryby) {
		this.entryby = entryby;
	}

	public Date getEntryDatetime() {
		return this.entryDatetime;
	}

	public void setEntryDatetime(Date entryDatetime) {
		this.entryDatetime = entryDatetime;
	}

	public Date getModifyDatetime() {
		return this.modifyDatetime;
	}

	public void setModifyDatetime(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public String getTownshipName() {
		return townshipName;
	}

	public void setTownshipName(String townshipName) {
		this.townshipName = townshipName;
	}

	public String getActivationKey() {
		return activationKey;
	}

	public void setActivationKey(String activationKey) {
		this.activationKey = activationKey;
	}

	public String getCountryName() {
		return countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	public String getStateName() {
		return stateName;
	}

	public void setStateName(String stateName) {
		this.stateName = stateName;
	}

	public String getCityName() {
		return cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	public int getNoOfMembers() {
		return noOfMembers;
	}

	public void setNoOfMembers(int noOfMembers) {
		this.noOfMembers = noOfMembers;
	}

	public String getPinCode() {
		return pinCode;
	}

	public void setPinCode(String pinCode) {
		this.pinCode = pinCode;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getNoOfBlocksWings() {
		return noOfBlocksWings;
	}

	public void setNoOfBlocksWings(String noOfBlocksWings) {
		this.noOfBlocksWings = noOfBlocksWings;
	}

	public String getRegisterNo() {
		return registerNo;
	}

	public void setRegisterNo(String registerNo) {
		this.registerNo = registerNo;
	}

	public String getColourCode() {
		return colourCode;
	}

	public void setColourCode(String colourCode) {
		this.colourCode = colourCode;
	}

	public String getImprintName() {
		return imprintName;
	}

	public void setImprintName(String imprintName) {
		this.imprintName = imprintName;
	}

	public String getLogoImage() {
		return logoImage;
	}

	public void setLogoImage(String logoImage) {
		this.logoImage = logoImage;
	}

	public String getIcoImage() {
		return icoImage;
	}

	public void setIcoImage(String icoImage) {
		this.icoImage = icoImage;
	}

	public String getMobileNo() {
		return mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	public String getEmailId() {
		return emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	public String getIsdCode() {
		return isdcode;
	}

	public void setIsdCode(String isdcode) {
		this.isdcode = isdcode;
	}

	public int getGroupCode() {
		return groupCode;
	}

	public void setGroupCode(int groupCode) {
		this.groupCode = groupCode;
	}

	public String getGstin() {
		return gstin;
	}

	public void setGstin(String gstin) {
		this.gstin = gstin;
	}

	public String getHsn() {
		return hsn;
	}

	public void setHsn(String hsn) {
		this.hsn = hsn;
	}


}
