package com.letspay.uam.persistense;

// default package
// Generated Jun 14, 2016 2:48:12 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;



/**
 * TownshipMstTbl generated by hbm2java
 */
public class TownshipMstTbl implements java.io.Serializable {

	private Integer townshipId;
	private String townshipUniqueId;
	private String townshipName;
	private Integer entryby;
	private Date entryDatetime;
	private Date modifyDatetime;

	private String noOfSociety;
	private String noOfFlats;
	private String address;
	private String pinCode;
	private String activationKey;
	private String countryName;
	private String stateName;
	private String cityName;
	private String townshiplogoname;
	private String townshipiconame;
	private String townshipcolourcode;
	
	private String countryFullName;
	private String stateFullName;
	private String cityFullName;
	private String pinFullCode;
	private String builderName;
	private String emailId;
	private String isdCode;
	private String mobileNo;
	private String landMark;
	private String imprintName;
	private String invrCountryid;
	private String invrStateid;
	private String invrCityid;
	private String invrPincodeid;
	
	public TownshipMstTbl() {
	}

	public TownshipMstTbl(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public TownshipMstTbl(
			 int townshipId,
			String townshipName,String activationKey,String countryname,String statename,String cityname ) {
		this.townshipId = townshipId;
		this.townshipName = townshipName;
		this.activationKey=activationKey;
		this.countryName=countryname;
		this.stateName=statename;
		this.cityName=cityname;
	}

	public Integer getTownshipId() {
		return this.townshipId;
	}

	public void setTownshipId(Integer townshipId) {
		this.townshipId = townshipId;
	}

	
	public String getTownshipUniqueId() {
		return this.townshipUniqueId;
	}

	public void setTownshipUniqueId(String townshipUniqueId) {
		this.townshipUniqueId = townshipUniqueId;
	}

	public String getTownshipName() {
		return this.townshipName;
	}

	public void setTownshipName(String townshipName) {
		this.townshipName = townshipName;
	}

	public Integer getEntryby() {
		return this.entryby;
	}

	public void setEntryby(Integer entryby) {
		this.entryby = entryby;
	}

	public Date getEntryDatetime() {
		return this.entryDatetime;
	}

	public void setEntryDatetime(Date entryDatetime) {
		this.entryDatetime = entryDatetime;
	}

	public Date getModifyDatetime() {
		return this.modifyDatetime;
	}

	public void setModifyDatetime(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public String getActivationKey() {
		return activationKey;
	}

	public void setActivationKey(String activationKey) {
		this.activationKey = activationKey;
	}

	public String getCountryName() {
		return countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	public String getStateName() {
		return stateName;
	}

	public void setStateName(String stateName) {
		this.stateName = stateName;
	}

	public String getCityName() {
		return cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	public String getTownshiplogoname() {
		return townshiplogoname;
	}

	public void setTownshiplogoname(String townshiplogoname) {
		this.townshiplogoname = townshiplogoname;
	}

	public String getTownshipiconame() {
		return townshipiconame;
	}

	public void setTownshipiconame(String townshipiconame) {
		this.townshipiconame = townshipiconame;
	}

	public String getTownshipcolourcode() {
		return townshipcolourcode;
	}

	public void setTownshipcolourcode(String townshipcolourcode) {
		this.townshipcolourcode = townshipcolourcode;
	}

	public String getNoOfSociety() {
		return noOfSociety;
	}

	public void setNoOfSociety(String noOfSociety) {
		this.noOfSociety = noOfSociety;
	}

	public String getNoOfFlats() {
		return noOfFlats;
	}

	public void setNoOfFlats(String noOfFlats) {
		this.noOfFlats = noOfFlats;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPinCode() {
		return pinCode;
	}

	public void setPinCode(String pinCode) {
		this.pinCode = pinCode;
	}

	public String getBuilderName() {
		return builderName;
	}

	public void setBuilderName(String builderName) {
		this.builderName = builderName;
	}

	public String getEmailId() {
		return emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	public String getIsdCode() {
		return isdCode;
	}

	public void setIsdCode(String isdCode) {
		this.isdCode = isdCode;
	}

	public String getMobileNo() {
		return mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	public String getLandMark() {
		return landMark;
	}

	public void setLandMark(String landMark) {
		this.landMark = landMark;
	}

	public String getImprintName() {
		return imprintName;
	}

	public void setImprintName(String imprintName) {
		this.imprintName = imprintName;
	}

	public String getCountryFullName() {
		return countryFullName;
	}

	public void setCountryFullName(String countryFullName) {
		this.countryFullName = countryFullName;
	}

	public String getStateFullName() {
		return stateFullName;
	}

	public void setStateFullName(String stateFullName) {
		this.stateFullName = stateFullName;
	}

	public String getCityFullName() {
		return cityFullName;
	}

	public void setCityFullName(String cityFullName) {
		this.cityFullName = cityFullName;
	}

	public String getPinFullCode() {
		return pinFullCode;
	}

	public void setPinFullCode(String pinFullCode) {
		this.pinFullCode = pinFullCode;
	}

	/**
	 * @return the invrCountryid
	 */
	public String getInvrCountryid() {
		return invrCountryid;
	}

	/**
	 * @param invrCountryid the invrCountryid to set
	 */
	public void setInvrCountryid(String invrCountryid) {
		this.invrCountryid = invrCountryid;
	}

	/**
	 * @return the invrStateid
	 */
	public String getInvrStateid() {
		return invrStateid;
	}

	/**
	 * @param invrStateid the invrStateid to set
	 */
	public void setInvrStateid(String invrStateid) {
		this.invrStateid = invrStateid;
	}

	/**
	 * @return the invrCityid
	 */
	public String getInvrCityid() {
		return invrCityid;
	}

	/**
	 * @param invrCityid the invrCityid to set
	 */
	public void setInvrCityid(String invrCityid) {
		this.invrCityid = invrCityid;
	}

	/**
	 * @return the invrPincodeid
	 */
	public String getInvrPincodeid() {
		return invrPincodeid;
	}

	/**
	 * @param invrPincodeid the invrPincodeid to set
	 */
	public void setInvrPincodeid(String invrPincodeid) {
		this.invrPincodeid = invrPincodeid;
	}


}
