package com.socialindia.complaints.persistance;

import java.util.Date;

/**
 * MvpComplaintsTbl generated by hbm2java
 */
public class ComplaintsTblVO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer complaintsId;
	private Integer usrRegTblByFromUsrId;
	private Integer groupMstTblByFromGroupId;
	private Integer groupMstTblByToGroupId;
	private Integer usrRegTblByToUsrId;
	private String complaintsTitle;
	private String complaintsDesc;
	private String complaintsFileName1;
	private String complaintsFileName2;
	private String complaintsFileName3;
	private String videoPath;
	private String complaintsOthersEmail;
	private Integer status;
	private Integer entryBy;
	private Integer complaintsCompleteBy;
	private String entryDatetime;
	private String modifyDatetime;
	private String complaintName;
	private String townshipname;
	private String societyname;
	private String grpname;
	private String complaint_to;
	private String cmpltfromgrpname;
	private String LaborMerchantid;
	private String LaborMerchantgrpid;
	private String Cmpltfrmgroupname;
	private String cmpltfrmusrid;
	private String cmpltclosereason;
	private String shrtdesc;

	public String getCmpltfromgrpname() {
		return cmpltfromgrpname;
	}

	public void setCmpltfromgrpname(String cmpltfromgrpname) {
		this.cmpltfromgrpname = cmpltfromgrpname;
	}

	/*public ComplaintsTblVO(int complaintid, String complaintName,
			String townshipname, String societyname, 
			String complaintdesc, String complainttttle, 
			int cmpltstatus, int cmpltentryby, String complaintsOthersEmail,String complaint_to,String lab_mercid,String lba_mergrpid,String Cmpltfrmgroupname,String cmpltfrmusrid,String cmpltclosereason) {
		this.complaintsId =complaintid;
		this.complaintName =complaintName;
		this.townshipname =townshipname;
		this.societyname =societyname;
		this.complaintsDesc=complaintdesc;
		this.complaintsTitle=complainttttle;
		this.status =cmpltstatus;
		this.entryBy=cmpltentryby;
		this.complaintsOthersEmail=complaintsOthersEmail;
		this.complaint_to=complaint_to;
		this.LaborMerchantid=lab_mercid;
		this.LaborMerchantgrpid=lba_mergrpid;
		this.Cmpltfrmgroupname=Cmpltfrmgroupname;
		this.cmpltfrmusrid=cmpltfrmusrid;
		this.cmpltclosereason=cmpltclosereason;
		// TODO Auto-generated constructor stub
	}*/

	public Integer getComplaintsId() {
		return this.complaintsId;
	}

	public void setComplaintsId(Integer complaintsId) {
		this.complaintsId = complaintsId;
	}

	

	

	

	

	public String getShrtdesc() {
		return shrtdesc;
	}

	public void setShrtdesc(String shrtdesc) {
		this.shrtdesc = shrtdesc;
	}

	public String getCmpltclosereason() {
		return cmpltclosereason;
	}

	public void setCmpltclosereason(String cmpltclosereason) {
		this.cmpltclosereason = cmpltclosereason;
	}

	public Integer getUsrRegTblByFromUsrId() {
		return usrRegTblByFromUsrId;
	}

	public void setUsrRegTblByFromUsrId(Integer usrRegTblByFromUsrId) {
		this.usrRegTblByFromUsrId = usrRegTblByFromUsrId;
	}

	public Integer getGroupMstTblByFromGroupId() {
		return groupMstTblByFromGroupId;
	}

	public void setGroupMstTblByFromGroupId(Integer groupMstTblByFromGroupId) {
		this.groupMstTblByFromGroupId = groupMstTblByFromGroupId;
	}

	public Integer getGroupMstTblByToGroupId() {
		return groupMstTblByToGroupId;
	}

	public void setGroupMstTblByToGroupId(Integer groupMstTblByToGroupId) {
		this.groupMstTblByToGroupId = groupMstTblByToGroupId;
	}

	public Integer getUsrRegTblByToUsrId() {
		return usrRegTblByToUsrId;
	}

	public void setUsrRegTblByToUsrId(Integer usrRegTblByToUsrId) {
		this.usrRegTblByToUsrId = usrRegTblByToUsrId;
	}

	public String getComplaintsTitle() {
		return this.complaintsTitle;
	}

	public void setComplaintsTitle(String complaintsTitle) {
		this.complaintsTitle = complaintsTitle;
	}

	public String getComplaintsDesc() {
		return this.complaintsDesc;
	}

	public void setComplaintsDesc(String complaintsDesc) {
		this.complaintsDesc = complaintsDesc;
	}

	

	public String getComplaintsFileName1() {
		return complaintsFileName1;
	}

	public void setComplaintsFileName1(String complaintsFileName1) {
		this.complaintsFileName1 = complaintsFileName1;
	}

	public String getComplaintsFileName2() {
		return complaintsFileName2;
	}

	public void setComplaintsFileName2(String complaintsFileName2) {
		this.complaintsFileName2 = complaintsFileName2;
	}

	public String getComplaintsFileName3() {
		return complaintsFileName3;
	}

	public void setComplaintsFileName3(String complaintsFileName3) {
		this.complaintsFileName3 = complaintsFileName3;
	}

	public String getVideoPath() {
		return this.videoPath;
	}

	public void setVideoPath(String videoPath) {
		this.videoPath = videoPath;
	}

	public String getComplaintsOthersEmail() {
		return this.complaintsOthersEmail;
	}

	public void setComplaintsOthersEmail(String complaintsOthersEmail) {
		this.complaintsOthersEmail = complaintsOthersEmail;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getEntryBy() {
		return this.entryBy;
	}

	public void setEntryBy(Integer entryBy) {
		this.entryBy = entryBy;
	}

	public Integer getComplaintsCompleteBy() {
		return this.complaintsCompleteBy;
	}

	public void setComplaintsCompleteBy(Integer complaintsCompleteBy) {
		this.complaintsCompleteBy = complaintsCompleteBy;
	}

	

	public String getEntryDatetime() {
		return entryDatetime;
	}

	public void setEntryDatetime(String entryDatetime) {
		this.entryDatetime = entryDatetime;
	}

	public String getModifyDatetime() {
		return this.modifyDatetime;
	}

	public void setModifyDatetime(String string) {
		this.modifyDatetime = string;
	}

	public String getComplaintName() {
		return complaintName;
	}

	public void setComplaintName(String complaintName) {
		this.complaintName = complaintName;
	}

	public String getTownshipname() {
		return townshipname;
	}

	public void setTownshipname(String townshipname) {
		this.townshipname = townshipname;
	}

	public String getSocietyname() {
		return societyname;
	}

	public void setSocietyname(String societyname) {
		this.societyname = societyname;
	}

	public String getGrpname() {
		return grpname;
	}

	public void setGrpname(String grpname) {
		this.grpname = grpname;
	}

	public String getComplaint_to() {
		return complaint_to;
	}

	public void setComplaint_to(String complaint_to) {
		this.complaint_to = complaint_to;
	}

	public String getLaborMerchantid() {
		return LaborMerchantid;
	}

	public void setLaborMerchantid(String laborMerchantid) {
		LaborMerchantid = laborMerchantid;
	}

	public String getLaborMerchantgrpid() {
		return LaborMerchantgrpid;
	}

	public void setLaborMerchantgrpid(String laborMerchantgrpid) {
		LaborMerchantgrpid = laborMerchantgrpid;
	}

	public String getCmpltfrmgroupname() {
		return Cmpltfrmgroupname;
	}

	public void setCmpltfrmgroupname(String cmpltfrmgroupname) {
		System.out.println("cmpltfromgrpcode ----- "+cmpltfrmgroupname);
		Cmpltfrmgroupname = cmpltfrmgroupname;
	}

	public String getCmpltfrmusrid() {
		return cmpltfrmusrid;
	}

	public void setCmpltfrmusrid(String cmpltfrmusrid) {
		this.cmpltfrmusrid = cmpltfrmusrid;
	}
	
	

}
