package com.socialindia.gatepass;

// default package
// Generated Dec 7, 2016 3:21:41 PM by Hibernate Tools 3.4.0.CR1





/**
 * MvpGatepassDetailTbl generated by hbm2java
 */
public class MvpGatepassDetailTbl implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private String passId;
	private String skillid;
	private String entryBy;
	private String idcardtype;
	private String gatepassNo;
	private String visitorName;
	private String visitorImage;
	private String passType;
	private String dateOfBirth;
	private String email;
	private String mobileNo;
	private String idCardNumber;
	private String issueDate;
	private String issueTime;
	private String expiryDate;
	private String description;
	private String noOfAccompanies;
	private String vehicleNumber;
	private String statusFlag;
	private String entryDatetime;
	private String modifyDatetime;
	private String modifyBy;
	private String visitorLocation;


	public String getVisitorLocation() {
		return visitorLocation;
	}

	public void setVisitorLocation(String visitorLocation) {
		this.visitorLocation = visitorLocation;
	}

	public String getPassId() {
		return passId;
	}

	public void setPassId(String passId) {
		this.passId = passId;
	}

	public String getSkillid() {
		return skillid;
	}

	public void setSkillid(String skillid) {
		this.skillid = skillid;
	}

	public String getEntryBy() {
		return entryBy;
	}

	public void setEntryBy(String entryBy) {
		this.entryBy = entryBy;
	}

	public String getIdcardtype() {
		return idcardtype;
	}

	public void setIdcardtype(String idcardtype) {
		this.idcardtype = idcardtype;
	}

	public String getGatepassNo() {
		return gatepassNo;
	}

	public void setGatepassNo(String gatepassNo) {
		this.gatepassNo = gatepassNo;
	}

	public String getVisitorName() {
		return visitorName;
	}

	public void setVisitorName(String visitorName) {
		this.visitorName = visitorName;
	}

	public String getVisitorImage() {
		return visitorImage;
	}

	public void setVisitorImage(String visitorImage) {
		this.visitorImage = visitorImage;
	}

	public String getPassType() {
		return passType;
	}

	public void setPassType(String passType) {
		this.passType = passType;
	}

	public String getDateOfBirth() {
		return dateOfBirth;
	}

	public void setDateOfBirth(String dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMobileNo() {
		return mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	public String getIdCardNumber() {
		return idCardNumber;
	}

	public void setIdCardNumber(String idCardNumber) {
		this.idCardNumber = idCardNumber;
	}

	public String getIssueDate() {
		return issueDate;
	}

	public void setIssueDate(String issueDate) {
		this.issueDate = issueDate;
	}

	public String getIssueTime() {
		return issueTime;
	}

	public void setIssueTime(String issueTime) {
		this.issueTime = issueTime;
	}

	public String getExpiryDate() {
		return expiryDate;
	}

	public void setExpiryDate(String expiryDate) {
		this.expiryDate = expiryDate;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getNoOfAccompanies() {
		return noOfAccompanies;
	}

	public void setNoOfAccompanies(String noOfAccompanies) {
		this.noOfAccompanies = noOfAccompanies;
	}

	public String getVehicleNumber() {
		return vehicleNumber;
	}

	public void setVehicleNumber(String vehicleNumber) {
		this.vehicleNumber = vehicleNumber;
	}

	public String getStatusFlag() {
		return statusFlag;
	}

	public void setStatusFlag(String statusFlag) {
		this.statusFlag = statusFlag;
	}

	public String getEntryDatetime() {
		return entryDatetime;
	}

	public void setEntryDatetime(String entryDatetime) {
		this.entryDatetime = entryDatetime;
	}

	public String getModifyDatetime() {
		return modifyDatetime;
	}

	public void setModifyDatetime(String modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public String getModifyBy() {
		return modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}





}
